services:
  dfs-aip:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./cache:/root/.cache/
      - /home/manuel/dfs/output:/app/output
      - /home/manuel/dfs/config.json:/app/config.json
    environment:
      # Set to "true" to run update when container starts
      - AUTO_UPDATE_ON_START=true

      # Optional: Custom cron schedule (default: daily at midnight)
      - CRON_SCHEDULE=0 0 * * *

    restart: unless-stopped
    network_mode: host

#volumes:
#  dfs-aip-cache: